# Generated by Django 4.1.6 on 2023-02-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('flexible_timings', models.BooleanField(default=False)),
                ('no_of_assets', models.PositiveSmallIntegerField()),
                ('asset_type', models.CharField(choices=[('LAPTOP', 'laptop'), ('TRAVEL_BAG', 'travel bag'), ('PACKAGE', 'package')], max_length=50)),
                ('asset_sensitivity', models.CharField(choices=[('HIGHLY_SENSITIVE', 'highly sensitive'), ('SENSITIVE', 'sensitive'), ('NORMAL', 'normal')], max_length=50)),
                ('whom_to_deliver', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('EXPIRED', 'expired')], default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShareTravelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('flexible_timings', models.BooleanField(default=False)),
                ('travel_medium', models.CharField(choices=[('BUS', 'bus'), ('CAR', 'car'), ('TRAIN', 'train')], max_length=50)),
                ('asset_quantity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied')], default='NOT_APPLIED', max_length=50)),
            ],
        ),
    ]
