# Generated by Django 4.1.6 on 2023-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assettransportrequest_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetravelinfo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
