# Generated by Django 4.1.6 on 2023-02-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sharetravelinfo_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransportrequest',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sharetravelinfo',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
